- name: Configure Docker on EC2 Instances
  hosts: all
  become: true
  connection: ssh

  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Stop any container using port 8484
      shell: |
        docker ps --filter "status=running" --format '{{.ID}} {{.Ports}}' \
        | grep 8484 \
        | awk '{print $1}' \
        | xargs -r docker stop
      ignore_errors: yes

    - name: Remove any stopped container using port 8484
      shell: |
        docker ps -a --filter "status=exited" --format '{{.ID}} {{.Ports}}' \
        | grep 8484 \
        | awk '{print $1}' \
        | xargs -r docker rm
      ignore_errors: yes

    - name: Deploy Docker container
      command: docker run -itd -p 8484:8082 sowjanyaparupally/healthcarenew:latest
